# GitHub LaTeX Makefile Compiler
# Author: Uri Arev <me@wantyapps.xyz>
name: GitHub LaTeX Makefile Compiler
run-name: ${{ github.actor }} is compiling your latex!
on: [push]
jobs:
  Clone-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update system
        run: |
          echo "Updating with apt..."
          sudo apt-get update
          echo "Updated"
      - name: Install needed tools
        run: |
          sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
          echo "Installed LaTeX and LaTeX tools"
      - name: Compile to PDF
        run: |
          echo "Compiling to AREE.pdf"
          make clean all
