# GitHub LaTeX Makefile Compiler
# Author: Uri Arev <me@wantyapps.xyz>
name: GitHub LaTeX Makefile Compiler
run-name: ${{ github.actor }} is compiling your latex!
on: [push]
jobs:
  Clone-Repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event."
      - run: echo "Cloning repository..."
      - name: Check out repository
        uses: actions/checkout@v3
      - run: echo "Repository cloned"
      - run: echo "Files in workspace"
      - run: ls ${{ github.workspace }}
      - name: Update system
      - run: echo "Updating with apt..."
      - run: sudo apt-get update
      - run: echo "Updated"
      - name: Install needed tools
      - run: sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - run: echo "Installed LaTeX and LaTeX tools"
      - name: Compile to PDF
      - run: echo "Compiling to AREE.pdf"
      - run: make clean all
